# Copyright 2017 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by puppet-codegen and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/container/property/cluster_name'
require 'google/container/property/string'
require 'puppet'

Puppet::Type.newtype(:gcontainer_kube_config) do
  @doc = "Generates a compatible Kuberenetes '.kube/config' file"

  autorequire(:gauth_credential) do
    credential = self[:credential]
    raise "#{ref}: required property 'credential' is missing" if credential.nil?
    [credential]
  end

  ensurable

  newparam :credential do
    desc <<-DESC
      A gauth_credential name to be used to authenticate with Google Cloud
      Platform.
    DESC
  end

  newparam(:project) do
    desc 'A Google Cloud Platform project to manage.'
  end

  newparam(:name, namevar: true) do
    # TODO(nelsona): Make this description to match the key of the object.
    desc 'The name of the KubeConfig.'
  end

  newproperty(:name, parent: Google::Container::Property::String) do
    desc 'The config file kubectl settings will be written to.'
  end

  newproperty(:cluster, parent: Google::Container::Property::ClusterNameRef) do
    desc 'A reference to Cluster resource'
  end

  newproperty(:zone, parent: Google::Container::Property::String) do
    desc 'The zone where the container is deployed'
  end

  newproperty(:context, parent: Google::Container::Property::String) do
    desc 'The name of the context. Defaults to cluster name.'
  end
end
